name: hello

dependencies:
  - haskell-say
  - base >= 4.7 && < 5
  - rio
  - rel8
  - aeson
  - bytestring
  - containers
  - http-media
  - lucid
  - mtl
  - servant
  - servant-rawm
  - servant-rawm-server
  - servant-server
  - stm
  - text
  - time
  - transformers
  - warp
  - wai
  - wai-app-static
  - wai-extra

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -Wno-name-shadowing
    - -fwarn-monomorphism-restriction
    - -Werror

default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude
  - TypeApplications


executables:
  haskell-hello:
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello

tests:
  hello-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello
    - base == 4.*
    - hspec
    - QuickCheck
    verbatim: |
      build-tool-depends:
          hspec-discover:hspec-discover
